# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DeadlineManager' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DeadlineManager
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'

  target 'DeadlineManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeadlineManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
